#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: Pinky human-only setup (issue #3)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

cd "$(git rev-parse --show-toplevel)"
KEYS_DIR="escrow/.keys"   # same dir escrow/scripts/lib.ts reads
VERCEL_SET=()

# set_vercel NAME VALUE [secret] pushes a production env var to the linked
# Vercel project. Secrets are stored as sensitive; failures are recorded.
set_vercel() {
  local name="$1" value="$2" kind="${3:-plain}" flag="--no-sensitive"
  [[ "$kind" == secret ]] && flag="--sensitive"
  if printf '%s' "$value" | vercel env add "$name" production --force --yes "$flag" >/dev/null 2>&1; then
    VERCEL_SET+=("$name")
    printf '  %s✓ set%s Vercel env %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env $name (vercel env add $name production)")
    warn "couldn't set Vercel env $name"
  fi
}

# sol_balance PUBKEY prints the devnet balance in SOL (0 on error).
sol_balance() {
  solana balance "$1" --url devnet 2>/dev/null | awk '{print $1}' | grep -E '^[0-9.]+$' || echo 0
}

banner "Pinky: demo repo, GitHub App, keys and deploy secrets"

# ── 1. Prerequisites ──────────────────────────────────────────────────────
stage "Check your tools"
missing=()
for cmd in git gh solana solana-keygen openssl vercel base64; do
  command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
done
if (( ${#missing[@]} )); then
  warn "missing tools: ${missing[*]}"
  note "Install them, then re-run. (solana: https://solana.com/docs/intro/installation)"
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  say "gh isn't logged in. Starting login."
  gh auth login
fi
touch .gitignore
for entry in .env .vercel; do
  grep -qxF "$entry" .gitignore || { printf '%s\n' "$entry" >> .gitignore; step "added $entry to .gitignore"; }
done
say "✓ tools present, gh authenticated, .env and .vercel are gitignored."
pause

# ── 2. Public demo repo ───────────────────────────────────────────────────
stage "Public demo repo"
say "Where non-collaborators will open issues and PRs against Pinky."
ask DEMO_REPO "Demo repo as owner/name [sivaratrisrinivas/pinky-demo]:"
: "${DEMO_REPO:=sivaratrisrinivas/pinky-demo}"
if gh repo view "$DEMO_REPO" >/dev/null 2>&1; then
  say "$DEMO_REPO already exists."
else
  if confirm "Create public repo $DEMO_REPO now?"; then
    gh repo create "$DEMO_REPO" --public --add-readme \
      --description "Demo repo for Pinky: refundable deposits against spam issues and PRs"
  else
    warn "Create it yourself at https://github.com/new, then re-run."
    exit 1
  fi
fi
visibility=$(gh repo view "$DEMO_REPO" --json visibility -q .visibility)
if [[ "$visibility" != "PUBLIC" ]]; then
  warn "$DEMO_REPO is $visibility, but the demo repo must be public."
  note "Fix at https://github.com/$DEMO_REPO/settings (Danger Zone → Change visibility), then re-run."
  exit 1
fi
write_env DEMO_REPO "$DEMO_REPO"
say "✓ https://github.com/$DEMO_REPO is public."
pause

# ── 3. Vercel project ─────────────────────────────────────────────────────
stage "Vercel project (deploy target)"
say "The webhook URL for the GitHub App comes from this project, so it comes first."
if ! vercel whoami >/dev/null 2>&1; then
  say "Logging in to Vercel."
  vercel login
fi
if [[ -f .vercel/project.json ]]; then
  say "Already linked to a Vercel project."
else
  step "Next: link or create a project. Pick your scope, answer 'N' to 'link to existing'"
  step "if it's new, and name it e.g. pinky-bot."
  vercel link
fi
open_url "https://vercel.com/dashboard"
step "Open the project → Settings → Domains. Copy the production domain,"
step "e.g. https://pinky-bot.vercel.app (no trailing path)."
ask APP_URL "Paste the production URL:"
APP_URL="${APP_URL%/}"
[[ "$APP_URL" == https://* ]] || { warn "URL must start with https://"; exit 1; }
write_env APP_URL "$APP_URL"
WEBHOOK_URL="$APP_URL/api/webhook"
note "The GitHub App webhook will point at $WEBHOOK_URL."
note "That path is the Vercel convention; change it in the App settings if the bot uses another."
pause

# ── 4. Register the GitHub App ────────────────────────────────────────────
stage "Register the GitHub App"
GITHUB_WEBHOOK_SECRET=$(_existing GITHUB_WEBHOOK_SECRET || true)
if [[ -z "$GITHUB_WEBHOOK_SECRET" ]]; then
  GITHUB_WEBHOOK_SECRET=$(openssl rand -hex 32)
  write_env GITHUB_WEBHOOK_SECRET "$GITHUB_WEBHOOK_SECRET"
fi
open_url "https://github.com/settings/apps/new"
step "GitHub App name: something unique, e.g. pinky-promise"
step "Homepage URL: https://github.com/sivaratrisrinivas/pinky"
step "Webhook → Active ✓"
step "Webhook URL:    $WEBHOOK_URL"
step "Webhook secret: $GITHUB_WEBHOOK_SECRET"
step "Repository permissions:"
step "    Issues → Read and write"
step "    Pull requests → Read and write"
step "    Metadata → Read-only (always on; covers collaborator-permission lookups)"
step "Subscribe to events (appear after you set permissions): Issues, Pull request, Issue comment"
step "Where can this GitHub App be installed? → Only on this account"
step "Click 'Create GitHub App'."
pause "Created it? Press Enter"
say "You land on the App's settings page."
step "Copy the numeric 'App ID' near the top."
ask GITHUB_APP_ID "Paste the App ID:"
step "Public link on that page looks like github.com/apps/<slug>. Copy just <slug>."
ask GITHUB_APP_SLUG "Paste the slug:"
[[ -n "$GITHUB_APP_ID" && -n "$GITHUB_APP_SLUG" ]] || { warn "Need both App ID and slug."; exit 1; }
write_env GITHUB_APP_ID "$GITHUB_APP_ID"
write_env GITHUB_APP_SLUG "$GITHUB_APP_SLUG"

# ── 5. Private key ────────────────────────────────────────────────────────
stage "GitHub App private key"
if [[ -n "$(_existing GITHUB_APP_PRIVATE_KEY_BASE64 || true)" ]] && ! confirm "A private key is already saved in $ENV_FILE. Import a new one?"; then
  say "Keeping the saved key."
else
  open_url "https://github.com/settings/apps/$GITHUB_APP_SLUG"
  step "Scroll to 'Private keys' → 'Generate a private key'. A .pem file downloads."
  note "On WSL the file is usually /mnt/c/Users/<you>/Downloads/<slug>.<date>.private-key.pem"
  PEM_PATH=""
  read -r -p "  Path to the downloaded .pem: " PEM_PATH || true
  PEM_PATH="${PEM_PATH/#\~/$HOME}"
  [[ -f "$PEM_PATH" ]] && grep -q 'BEGIN .*PRIVATE KEY' "$PEM_PATH" || { warn "That isn't a PEM private key file."; exit 1; }
  # Base64 so the multi-line PEM survives .env and Vercel as one line.
  write_env GITHUB_APP_PRIVATE_KEY_BASE64 "$(base64 < "$PEM_PATH" | tr -d '\n')"
  if confirm "Delete the downloaded .pem now? (the key now lives in $ENV_FILE)"; then
    rm -f -- "$PEM_PATH" && say "✓ deleted $PEM_PATH"
  else
    SKIPPED+=("delete the downloaded private key file $PEM_PATH")
  fi
fi

# ── 6. Install on the demo repo only ──────────────────────────────────────
stage "Install the App on the demo repo only"
open_url "https://github.com/apps/$GITHUB_APP_SLUG/installations/new"
step "Choose your account."
step "Select 'Only select repositories' → pick ${DEMO_REPO#*/} (just that one)."
step "Click 'Install'."
if ! confirm "Installed on $DEMO_REPO only (not 'All repositories')?"; then
  SKIPPED+=("install the App on $DEMO_REPO only: https://github.com/apps/$GITHUB_APP_SLUG/installations/new")
fi

# ── 7. Arbiter + faucet keypairs, devnet SOL ──────────────────────────────
stage "Arbiter and faucet keypairs (devnet)"
mkdir -p "$KEYS_DIR"
for name in arbiter faucet; do
  file="$KEYS_DIR/$name.json"
  if [[ -f "$file" ]]; then
    say "$name keypair already exists, reusing it."
  else
    solana-keygen new --no-bip39-passphrase --silent --outfile "$file" >/dev/null
    chmod 600 "$file"
    say "✓ created $file"
  fi
done
ARBITER_PUBKEY=$(solana-keygen pubkey "$KEYS_DIR/arbiter.json")
FAUCET_PUBKEY=$(solana-keygen pubkey "$KEYS_DIR/faucet.json")
write_env ARBITER_PUBKEY "$ARBITER_PUBKEY"
write_env FAUCET_PUBKEY "$FAUCET_PUBKEY"
write_env ARBITER_SECRET_KEY "$(tr -d '\n ' < "$KEYS_DIR/arbiter.json")"
write_env FAUCET_SECRET_KEY "$(tr -d '\n ' < "$KEYS_DIR/faucet.json")"
note "Arbiter: $ARBITER_PUBKEY (npm run setup-project in escrow/ reuses $KEYS_DIR/arbiter.json)"
note "Faucet:  $FAUCET_PUBKEY"
say "Funding the faucet wallet with devnet SOL..."
solana airdrop 2 "$FAUCET_PUBKEY" --url devnet >/dev/null 2>&1 || true
bal=$(sol_balance "$FAUCET_PUBKEY")
if ! awk -v b="$bal" 'BEGIN{exit !(b >= 1)}'; then
  warn "CLI airdrop didn't land (devnet rate limits). Use the web faucet instead."
  open_url "https://faucet.solana.com"
  step "Paste $FAUCET_PUBKEY, choose Devnet, request 2 SOL (repeat if needed)."
  pause "Done? Press Enter to re-check the balance"
  bal=$(sol_balance "$FAUCET_PUBKEY")
fi
if awk -v b="$bal" 'BEGIN{exit !(b >= 1)}'; then
  say "✓ faucet holds $bal SOL on devnet."
else
  SKIPPED+=("fund faucet $FAUCET_PUBKEY with devnet SOL (balance: $bal)")
fi
pause

# ── 8. Deploy-target secrets ──────────────────────────────────────────────
stage "Push secrets to Vercel"
say "Writes these as production env vars on the linked Vercel project:"
note "GITHUB_APP_ID, GITHUB_APP_SLUG, GITHUB_WEBHOOK_SECRET, GITHUB_APP_PRIVATE_KEY_BASE64,"
note "ARBITER_SECRET_KEY, FAUCET_SECRET_KEY (secrets are stored as Vercel 'sensitive')"
if confirm "Push them now? (overwrites any existing values of the same name)"; then
  set_vercel GITHUB_APP_ID "$GITHUB_APP_ID"
  set_vercel GITHUB_APP_SLUG "$GITHUB_APP_SLUG"
  set_vercel GITHUB_WEBHOOK_SECRET "$GITHUB_WEBHOOK_SECRET" secret
  set_vercel GITHUB_APP_PRIVATE_KEY_BASE64 "$(_existing GITHUB_APP_PRIVATE_KEY_BASE64)" secret
  set_vercel ARBITER_SECRET_KEY "$(_existing ARBITER_SECRET_KEY)" secret
  set_vercel FAUCET_SECRET_KEY "$(_existing FAUCET_SECRET_KEY)" secret
else
  SKIPPED+=("push secrets to Vercel (re-run this wizard; it's idempotent)")
fi
pause

# ── 9. Colosseum Arena profile ────────────────────────────────────────────
stage "Colosseum Arena project profile"
open_url "https://arena.colosseum.org"
note "If that URL doesn't load, find the Arena link on the hackathon's event page."
step "Log in, open your project (or create it), and fill in the profile:"
step "name: Pinky · tagline: pinky promise this isn't spam"
step "repo: https://github.com/sivaratrisrinivas/pinky"
step "description: first-time contributors post a small refundable devnet USDC deposit;"
step "maintainers refund good-faith issues and forfeit spam."
if ! confirm "Project profile saved on Arena?"; then
  SKIPPED+=("fill in the Colosseum Arena project profile")
fi

finish
(( ${#VERCEL_SET[@]} )) && { note "set ${#VERCEL_SET[@]} Vercel env var(s): ${VERCEL_SET[*]}"; printf '\n'; }
note "Next: cd escrow && npm run setup-project -- $DEMO_REPO"
printf '\n'
